### ISSUE TITLE
(reason)

### ISSUE THREAD

**Issue by mm108** [simplec-dev/AndroidPowerControls#2]
hi

Can I know that type of variable is 'reason' in the below statement?

window.plugins.powercontrols.reboot(reason)

Thanks,
M&M

**Comment by simplec-dev** [comment]
Look in the android docs.  Regardless, it doesn't matter.  It won't work unless the device is rooted.

Thank you,

Doug Nelson
VP of Technology
SimpleC, LLC
dnelson@simplec.commailto:dnelson@simplec.com
(404) 966-1604

On Aug 4, 2015, at 4:59 AM, m-menon <notifications@github.com<mailto:notifications@github.com>> wrote:

hi

Can I know that type of variable is 'reason' in the below statement?

window.plugins.powercontrols.reboot(reason)

Thanks,
M&M

**Comment by mm108** [comment]
okie thanks
